cosmos/cosmos/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = "Home"),
    path('accounts/', include('accounts.urls', namespace = "accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name = "Test"),
    path('', views.ThanksPage.as_view(), name = "Thanks"),
    path('posts/', include("posts.urls", namespace="posts")),
    path('clusters/',include("clusters.urls", namespace="clusters")),

]


if settings.DEBUG:
       
       import debug_toolbar
       urlpatterns += [
              path('__debug__/', include(debug_toolbar.urls)),
              ]

cosmos/posts/urls.py
from django.urls import path, re_path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete")
]

cosmos/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka

from clusters.models import Cluster
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name="posts",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField(max_length=200)
    message_html = models.TextField(editable=False)
    cluster = models.ForeignKey(Cluster,related_name="posts",null=True,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        print(repr(self.message), type(self.message))
        return str(self.message) if self.message else ''

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

cosmos/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.http import Http404
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    ListView,
    RedirectView
)
from django.contrib import messages
from braces.views import SelectRelatedMixin
#from . import forms

from . import models


from django.contrib.auth import get_user_model

User = get_user_model()

class PostList(SelectRelatedMixin,ListView):
    model = models.Post
    select_related = ('user', 'cluster')

class UserPosts(ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))

        except User.DoesNotExist:
            raise Http404
        
        else:
            return self.post_user.posts.all()
            
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,DetailView):
    model = models.Post
    select_related = ('user','cluster')

    def get_queryset(self,**kwargs):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,CreateView):
    
    model = models.Post
    fields = ('message','cluster',)
    #form_class = forms.PostForm

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,DeleteView):

    model = models.Post
    select_related = ('user', 'cluster')   

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

cosmos/posts/templates/posts/_post.html
<div class="post media">
    <h3>{{ post.message_html|safe }}</h3>
        <div class="media-body">
            <strong>{{ post.user.username }}</strong>
            <h5 class="media-heading">
                <span class="username"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></span>
                <time class="time"><a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a></time>
                {% if post.cluster %}
                <span class="group-name">in <a href="#">{{ post.cluster.name }}</a></span>
                {% endif %}
            </h5>
    
    
            <div class="media-footer">
                {% if user.is_authenticated and post.user == user and not hide_delete %}
                    <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
                        <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
                        <span class="text-danger icon-label">Delete</span>
                    </a>
                {% endif %}
            </div>
        </div>
</div>
    

cosmos/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block mainContent %}
<div class="posts-page">
	<div class="container">
		<div class="row">
			{% block prepost%}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post%}{% endblock %}
		</div>
	</div>
</div>
{% endblock %}

cosmos/posts/templates/posts/post_delete.html
{% extends "posts/post_base.html" %}


{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

cosmos/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div class="col-md-8">
    {% include "posts/_post.html" %}
</div>
{% endblock %}

cosmos/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap3 %}

{% block post_content %}

<h4>Create New Post</h4>

<form method="POST" action="{% url 'posts:create' %}" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>

{% endblock %}

cosmos/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load humanize %}

{% block pre_post_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Clusters</h5>
			<ul class="list-unstyled">
				{% for member_cluster in get_user_clusters %}
				<li class="group li-with-bullet">
					<a href="{% url 'clusters:single' slug=member_cluster.cluster.slug %}">{{ member_cluster.cluster.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All Cluster</h5>
			<ul class="list-unstyled">
				{% for other_cluster in get_other_clusters %}
					<li class="group li-with-bullet"><a href="{% url 'clusters:single' slug=other_cluster.slug %}">{{ other_cluster.name }}</a></li>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>

{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

cosmos/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}