cosmos/clusters/urls.py
from django.urls import path, re_path
from . import views

app_name = 'clusters'

urlpatterns = [
    path('',views.ListClusters.as_view(),name="all"),
    path('new/',views.CreateCluster.as_view(),name="create"),
    re_path(r"posts/in/(?P<slug>[-\w]+)/$",views.SingleCluster.as_view(),name="single"),
    re_path(r"join/(?P<slug>[-\w]+)/$",views.JoinCluster.as_view(),name="join"),
    re_path(r"leave/(?P<slug>[-\w]+)/$",views.LeaveCluster.as_view(),name="leave"),
]

cosmos/cosmos/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name = "Home"),
    path('accounts/', include('accounts.urls', namespace = "accounts")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name = "Test"),
    path('', views.ThanksPage.as_view(), name = "Thanks"),
    path('posts/', include("posts.urls", namespace="posts")),
    path('clusters/',include("clusters.urls", namespace="clusters")),

]


if settings.DEBUG:
       
       import debug_toolbar
       urlpatterns += [
              path('__debug__/', include(debug_toolbar.urls)),
              ]

cosmos/posts/urls.py
from django.urls import path, re_path

from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    re_path(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    re_path(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    re_path(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete")
]

cosmos/clusters/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
import misaka
from django.urls import reverse

from django import template
register = template.Library()

User = get_user_model()

class Cluster(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode= True, unique= True)
    description = models.CharField(max_length=300,blank= True, default= '' )
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through= 'ClusterMember')

    def __str__(self):
        self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('clusters:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name',]

class ClusterMember(models.Model):
    cluster = models.ForeignKey(
        Cluster,
        related_name = 'memberships',
        on_delete=models.CASCADE
    )

    user = models.ForeignKey(
        User,
        related_name = 'user_clusters',
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('cluster','user')

cosmos/clusters/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
    ListView,
    RedirectView
)
#from django.views.generic import DetailView,ListView,RedirectView
#from django.views.generic import ListView  
#from django.views.generic import RedirectView 
from clusters.models import Cluster,ClusterMember
from django.contrib import messages

class CreateCluster(LoginRequiredMixin,CreateView):
    fields = ('name', 'description')
    model = Cluster

class SingleCluster(DetailView):
    model = Cluster

class ListClusters(ListView):
    model = Cluster
    #queryset = model.objects.order_by('name')

class JoinCluster(LoginRequiredMixin,RedirectView):
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse("clusters:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        cluster = get_object_or_404(Cluster,slug=self.kwargs.get("slug"))

        try:
            ClusterMember.objects.create(user=self.request.user,cluster=cluster)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(cluster.name)))

        else:
            messages.success(self.request,"You are now a member of the {} cluster.".format(cluster.name))

        return super().get(request, *args, **kwargs)


class LeaveCluster(LoginRequiredMixin,RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("clusters:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = ClusterMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except ClusterMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

cosmos/clusters/templates/clusters/cluster_base.html
{% extends "base.html" %}

{% block mainContent %}

<div class = "container">
    <div class = "row">
        {% block precluster %} {% endblock%}
        {% block cluster_content %} {% endblock%}
        {% block postcluster %} {% endblock%}
    </div>
</div>

{% endblock %}

cosmos/clusters/templates/clusters/cluster_detail.html
{% extends "clusters/cluster_base.html" %}
{% block precluster %}

<h1>{{cluster.name}}</h1>
<h2>Subscibers: {{cluster.members.count}}</h2>

<div class = "content">

    {% if user in cluster.members.all %}
        <a href="{% url 'clusters:leave' slug=cluster.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
	{% else %}
		<a href="{% url 'clusters:join' slug=cluster.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
	{% endif %}


</div>

{% endblock %}


{% block cluster_content %}

<div class="col-md-8">

	{% if cluster.posts.count == 0 %}
	    <h2>No posts in this cluster yet!</h2>
	{% else %}
		{% for post in cluster.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}
	{% endif %}

</div>

{% endblock %}

cosmos/clusters/templates/clusters/cluster_form.html
{% extends "clusters/cluster_base.html" %}
{% load bootstrap3 %}

{% block cluster_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'clusters:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

cosmos/clusters/templates/clusters/cluster_list.html
{% extends "clusters/cluster_base.html" %}

{% block precluster %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Clusters</h2>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'clusters:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Cluster!</a>
	{% endif %}
</div>
{% endblock %}

{% block cluster_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for cluster in object_list %}
		  <a class="list-group-item" href="{% url 'clusters:single' slug=cluster.slug %}">
			     <h3 class="title list-group-item-heading">{{ cluster.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ cluster.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ cluster.members.count }}</span> member{{ cluster.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ cluster.posts.count }}</span> post{{ cluster.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}